API300 Enclosure
HewlettPackard/oneview-chef pull request #141
Opened 2017-01-25 13:15 UTC by tmiotto

### Description
Adds support to enclosure in API300

### Issues Resolved
#140

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [ ] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

2017-01-26 21:11 UTC, jsmartt approved these changes

2017-01-26 21:12 UTC, jsmartt requested changes
@tmiotto , can you add the new patch option to the README? After that I'm good with this

2017-01-27 16:41 UTC, jsmartt approved these changes
OK @tmiotto , I updated the README with the new properties and actions. I think it's fine as-is, but I did have a few questions:
 - Is the `value` property in the patch action not required? It doesn't look like it's validated, so could potentially be `nil`. Just wanted to make sure that's what you intended.
 - For the `:refresh` action, there are defaults being set in the provider class, but it seems easier and more transparent to set the defaults in the actual resource file, right?

2017-01-30 13:05 UTC, tmiotto commented
The `value` can really be `nil` in some patch actions.

Regarding the `:refresh`, it makes total sense, I'll send a patch to fix it.

2017-01-30 15:59 UTC, merged