Server Profile OS Deployment
HewlettPackard/oneview-chef pull request #227
Opened 2017-03-27 17:03 UTC by tmiotto

### Description
Add support to OS Deployment Plans in the oneview_server_profile resource.

### Issues Resolved
#217

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [ ] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

2017-03-27 19:55 UTC, fgbulsoni commented on examples/image_streamer/server_profile_deploy.rb
> +# Instantiate a new server profile from the previously created template 'WebServerTemplate1'
Would probably be good to add a comment specifying that this SPT must be created prior to running the cookbook, maybe somewhere along the start of the cookbook?

2017-03-27 20:00 UTC, fgbulsoni approved these changes
Overall looks good. I'd suggest adding a comment at the start of the example file about what is required for this example to be run, but other than that looking good :sparkles: :sparkles:

2017-03-27 20:28 UTC, jsmartt commented on examples/image_streamer/server_profile_deploy.rb
> +end
Can you do these last 2 resources with just the oneview_server_profile resource? Something like:

```ruby
oneview_server_profile 'ESXi - WebServer1' do
  client oneview_client
  server_profile_template 'WebServerTemplate1'
  server_hardware 'Enclosure1, bay 1'
  os_deployment_plan 'ESXi - Build simple environment'
end
```

2017-03-27 20:31 UTC, jsmartt requested changes

2017-03-27 20:31 UTC, jsmartt commented on README.md
> +- **deployment_plan** (String) Optional - Specify the Deployment Plan to be applied with the Server Profile. The OS Deployment Plan need to be created in Image Streamer appliance. See the [examples](
Make a note about this property being supported only in API300+. Also, change the link text from "examples" to "example"

2017-03-28 13:06 UTC, jsmartt approved these changes
👍

2017-03-28 13:28 UTC, merged