Support to Oneview Event
HewlettPackard/oneview-chef pull request #239
Opened 2017-06-20 17:53 UTC by ricardogpsf

### Description
Support to Oneview Event using api 200 and api 300

### Issues Resolved
Fixes #238 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [x] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

2017-06-20 21:18 UTC, tmiotto requested changes

2017-06-20 21:18 UTC, tmiotto commented on resources/event.rb
> +  OneviewCookbook::Helper.do_resource_action(self, :Event, :create)
Do not call the create directly if you are not overriding the method to do the existence check.

Please call the create_or_update, or if needed override the :create method in the providers.

2017-06-21 16:06 UTC, ricardogpsf commented on resources/event.rb
> +  OneviewCookbook::Helper.do_resource_action(self, :Event, :create)
But no make sense update the event, because the event just can be created and cannot updated

2017-06-27 12:41 UTC, tmiotto approved these changes

2017-06-27 13:42 UTC, merged