LIG Uplink ICM types & enclosure index support
HewlettPackard/oneview-chef pull request #244
Opened 2017-07-24 19:18 UTC by vranystepan

### Description
Added support for uplink ports with specified `:type` and `:enclosure_index` as mentioned in #225 

### Issues Resolved
- #225 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

2017-07-25 10:02 UTC, vranystepan commented
Functional test with the [example](https://github.com/vranystepan/oneview-chef/blob/lig_uplink_icm_types/examples/logical_interconnect_group_synergy.rb) works. 

**Result:** 

<img width="331" alt="result" src="https://user-images.githubusercontent.com/88839/28566946-0cd3ae0e-7131-11e7-9195-a06cfd0ed60a.png">

2017-08-17 13:23 UTC, tmiotto commented
@vranystepan  is this PR ready to be reviewed?

2017-08-20 06:54 UTC, vranystepan commented
@tmiotto yes

2017-08-21 12:41 UTC, tmiotto requested changes
Great job @vranystepan ! ✨ 

There are just few things to be changed, and also, please rebase your code and re-run the `rake test` again, some gems were updated and this code may be affected by these changes.

2017-08-21 12:41 UTC, tmiotto commented on examples/logical_interconnect_group_synergy.rb
> +  })
I guess these `{ }` are redundant.

When you pass `data( ... )` like that, without a space between the tag and parentheses, it automatically transforms the content into a hash.

2017-08-21 12:41 UTC, tmiotto commented on libraries/resource_providers/api200/logical_interconnect_group_provider.rb
> +            enclosure_index = link[:enclosure_index] ? link[:enclosure_index] : 1
You can simply use:
```ruby
 enclosure_index = link[:enclosure_index] || 1
```

2017-08-21 12:41 UTC, tmiotto commented on libraries/resource_providers/api200/logical_interconnect_group_provider.rb
> +            type = link[:type] ? link[:type] : nil
You can simply use:
```ruby
type = link[:type]
```

2017-08-21 12:41 UTC, tmiotto commented on spec/fixtures/cookbooks/oneview_test_api300_synergy/recipes/logical_interconnect_group_load_resource_with_synergy_properties.rb
> +# Recipe:: logical_interconnect_group_load_resource_with_properties
Update the Cookbook name and the Recipe name

2017-08-21 12:41 UTC, tmiotto commented on spec/unit/resources/logical_interconnect_group/load_resource_with_synergy_properties_spec.rb
> +describe 'oneview_test_api300_synergy::logical_interconnect_group_load_resource_with_synergy_properties' do
Please move this entire describe to the file `load_resource_with_properties_spec.rb`, and delete this file thereafter.

2017-08-27 18:30 UTC, vranystepan commented
@tmiotto I've made these changes .... anyway (after the rebase) it seems to be a bit messy. Is it normal or should I start over? :grin:

2017-08-28 06:52 UTC, vranystepan commented
PS I'm willing to create a new fork and new Pull Request ... that's not so big deal :)

2017-08-28 12:16 UTC, fgbulsoni commented
@vranystepan it does look messy as it is now, since it is pointing 63 commits and 51 files changed 😨 
If possible, my suggestion would be:
1. Create a new local branch based on the updated Master
2. Add your changes to it
3. Force push to this branch. 
No need to close/reopen the PR in that case, and it should be clean then.

2017-08-28 16:39 UTC, vranystepan commented
@fgbulsoni Sounds great! Will do. Thank you very much for your advice :)

2017-08-28 18:22 UTC, vranystepan commented
@tmiotto Ufff :sweat: .... it should be OK now. Could you review please?

2017-08-29 12:56 UTC, tmiotto approved these changes

2017-08-29 12:58 UTC, tmiotto commented
@vranystepan  It's fine now! 😄 

Just resolve the conflicts in the CHANGELOG and :shipit:

2017-08-29 16:43 UTC, merged