API 500 Scopes support
HewlettPackard/oneview-chef pull request #245
Opened 2017-08-16 19:06 UTC by ricardogpsf

### Description
Adding support to scopes of API 500

### Issues Resolved

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [ ] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

2017-08-16 19:56 UTC, ricardogpsf commented
This code is not ready yet. It's just to other people verify if the way is correct.

2017-08-17 13:24 UTC, tmiotto commented on attributes/default.rb
> +default['oneview']['api_version'] = 300
Don't do it, it is a breaking change

2017-08-21 13:32 UTC, tmiotto requested changes

2017-08-21 13:32 UTC, tmiotto commented on CHANGELOG.md
> +  - oneview_scope resource
There is no need to say again it is a resource if you're saying in the sentence before they're all resources.

Please list only the resource name, e.g. `- oneview_scope`

2017-08-21 13:32 UTC, tmiotto commented on libraries/oneview_helper.rb
> +    # @return [Class] Resource class or nil if not found
This doc is wrong, it does not returns 'nil' f not found, it raises an error.

2017-08-21 13:32 UTC, tmiotto commented on libraries/resource_providers/api500.rb
> +    # @return [Class] Resource class or nil if not found
Same issues here

2017-08-22 14:44 UTC, tmiotto approved these changes

2017-08-22 15:54 UTC, merged