Upgraded gems and fixed consequences
HewlettPackard/oneview-chef pull request #249
Opened 2017-08-17 18:30 UTC by tmiotto

### Description
Updates the gems, includig the oneview-sdk (5.0.0).

Also fixes all the consequences (mainly new rucobop style).

### Issues Resolved
#246 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [ ] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

2017-08-17 19:15 UTC, fgbulsoni requested changes

2017-08-17 19:15 UTC, fgbulsoni commented on Gemfile
> +gem 'foodcritic', '~> 11.3'
This is causing an error in the CI for Ruby 2.1:
```
    foodcritic (~> 11.3) was resolved to 11.3.0, which depends on
      ruby (>= 2.2.2)
```
Should likely add it in a condition, like the guard gem, and to use the latest version in Ruby 2.2+ and use the latest possible to Ruby 2.1.

2017-08-18 12:46 UTC, tmiotto commented on Gemfile
> +gem 'foodcritic', '~> 11.3'
Actually it is not the best approach.

I'll lower the version binding, it is not safe to leave it causing issues as new versions appears in the new rubies. (same as rubocop rules)

2017-08-18 13:33 UTC, fgbulsoni commented on Gemfile
> +gem 'foodcritic', '~> 11.3'
> I'll lower the version binding, it is not safe to leave it causing issues as new versions appears in the new rubies

Right, but that version is only causing issues in Ruby 2.1. 
Should we really stick to a lower version of that gem on all rubies, just for ruby 2.1 compatibility? 
Also, if it actually dropped ruby 2.1 support, that'd mean we'd be stuck on that version permanently.

2017-08-18 13:42 UTC, tmiotto commented on Gemfile
> +gem 'foodcritic', '~> 11.3'
r

> Should we really stick to a lower version of that gem on all rubies, just for ruby 2.1 compatibility?

Yes, the rules may change from one version to another, and we do not want to keep two different rule files and so on.

2017-08-18 16:36 UTC, fgbulsoni approved these changes

2017-08-18 16:37 UTC, merged