Support for Datacenter - API500
HewlettPackard/oneview-chef pull request #277
Opened 2017-08-25 13:47 UTC by ricardogpsf

### Description
API500 Support for Datacenter

### Issues Resolved
#276 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

2017-08-25 20:30 UTC, aalexmonteiro approved these changes
Looks good for me.

2017-08-28 12:01 UTC, fgbulsoni requested changes

2017-08-28 12:01 UTC, fgbulsoni commented on examples/datacenter.rb
> +# NOTE: It's necessary there is a Rack with name 'Rack_1' added before
Avoid "It's", *it is* should be used in these cases.
Suggested rewording:

*NOTE: This example requires a Rack named "Rack_1" in the appliance.*  

~~or something similar

2017-08-28 14:27 UTC, fgbulsoni approved these changes

2017-08-28 14:29 UTC, fgbulsoni commented on libraries/resource_providers/api500/synergy/datacenter_provider.rb
> +      # Datacenter API500 Synergy resource provider methods
Why does the Synergy has a comment so different from the C7000?
`Datacenter API500 Synergy resource provider methods`
vs
`Datacenter API500 C7000 provider`
Suggestion: standardize it

2017-08-28 16:57 UTC, merged