Using helper method of StoragePool API500 into Provider
HewlettPackard/oneview-chef pull request #344
Opened 2017-10-10 19:14 UTC by ricardogpsf

### Description
When StoragePoolProvider is loading StorageSystem to set it into StoragePool resource instance, the called method of StoragePool instance is now `set_storage_sytem`.

ATTENTION: 
- This PR cannot be merge for now, because the [PR ] of `oneview-sdk-ruby` must be merge before.
- The tests are failling (consequently, the build) because the reason cited above.
- For testing that changes you must change the path to oneview-sdk gem into your Gemfile, like code below:
```ruby
gem 'oneview-sdk', path: '/oneview-sdk-ruby'
```

### Issues Resolved
Fixes #343 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

2017-10-10 19:21 UTC, aalexmonteiro requested changes

2017-10-10 19:21 UTC, aalexmonteiro commented on spec/unit/resources/storage_pool/add_for_management_spec.rb
> +    allow_any_instance_of(provider_class).to receive(:load_resource).with(:StorageSystem, anything).and_return(base_sdk::StorageSystem.new(client500, uri: '/sotrage-system/1'))
```/sotrage-system``` => ```/storage-system```

2017-10-10 19:21 UTC, aalexmonteiro commented on spec/unit/resources/storage_pool/refresh_spec.rb
> +        .and_return(OneviewSDK::API500::Synergy::StorageSystem.new(client500, uri: '/sotrage-system/1'))
```/sotrage-system``` => ```/storage-system```

2017-10-10 19:21 UTC, aalexmonteiro commented on spec/unit/resources/storage_pool/remove_from_management_spec.rb
> +    allow_any_instance_of(provider_class).to receive(:load_resource).with(:StorageSystem, anything).and_return(base_sdk::StorageSystem.new(client500, uri: '/sotrage-system/1'))
```/sotrage-system``` => ```/storage-system```

2017-10-10 19:21 UTC, aalexmonteiro commented on spec/unit/resources/storage_pool/update_spec.rb
> +    allow_any_instance_of(provider_class).to receive(:load_resource).with(:StorageSystem, anything).and_return(base_sdk::StorageSystem.new(client500, uri: '/sotrage-system/1'))
```/sotrage-system``` => ```/storage-system```

2017-10-11 18:04 UTC, aalexmonteiro commented
Just test this when the SDK release is made to make sure everything is working well.

2017-10-11 19:32 UTC, tmiotto approved these changes
🦄

2017-10-11 19:35 UTC, aalexmonteiro approved these changes

2017-10-11 19:41 UTC, ricardogpsf commented
Let's generate the release of oneview-ruby-sdk to the "building" stop breaking

2017-10-11 20:08 UTC, merged