Feature/firmware
HewlettPackard/oneview-chef pull request #44
Opened 2016-09-27 13:05 UTC by hdiomede

### Description
Adds Firmware driver resource implementation and integrate firmware bundle with it in the same CHEF resource

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [ ] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

2016-09-27 19:51 UTC, jsmartt commented on spec/unit/resources/matchers_spec.rb
> +    expect(chef_run).to_not delete_oneview_network_set('')
Not sure if you meant to add this in here or not, but it's actually defined below also (in alphabetical order)

2016-09-29 20:53 UTC, tmiotto requested changes

2016-09-29 20:53 UTC, tmiotto commented on README.md
> +  action :create_custom_spp
Where are the other actions?

2016-09-29 20:53 UTC, tmiotto commented on resources/firmware.rb
> +  if item.nil?
Wouldn't make more sense replacing:
```Ruby
if item.nil?
  do X
else
  do Y
end
```

for:

```Ruby
if item
  do Y
else
  do X
end
```

???

2016-09-29 20:53 UTC, tmiotto commented on resources/firmware.rb
> +  raise "Unspecified property: 'spp_name' or 'spp_file'. Please set it before attempting this action." unless spp_name || spp_file
Both are required? Or just one of the variables?

2016-09-29 20:53 UTC, tmiotto commented on resources/firmware.rb
> +    raise "Unspecified property: 'hotfixes_names' or 'hotfixes_files'. Please set it before attempting this action."
You're checking if they are **empty** here, but the exception raised says they are **unspecified** (nil)

2016-09-30 11:42 UTC, hdiomede commented on resources/firmware.rb
> +  if item.nil?
Yes, thanks!

2016-09-30 12:48 UTC, hdiomede commented on resources/firmware.rb
> +  raise "Unspecified property: 'spp_name' or 'spp_file'. Please set it before attempting this action." unless spp_name || spp_file
Only one

2016-09-30 20:21 UTC, tmiotto approved these changes

2016-10-03 12:41 UTC, tmiotto approved these changes

2016-10-03 12:44 UTC, merged