Implementation for power device
HewlettPackard/oneview-chef pull request #46
Opened 2016-09-29 10:35 UTC by hdiomede

### Description
Implements power delivery device resource

### Issues Resolved
#45 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [ ] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

2016-09-29 20:22 UTC, tmiotto requested changes

2016-09-29 20:22 UTC, tmiotto commented on examples/power_device.rb
> +oneview_power_device '127.0.0.1 ' do
This is the same as the example before, something missing here maybe?

2016-09-29 20:22 UTC, tmiotto commented on resources/power_device.rb
> +    converge_by "Adding #{resource_name} '#{name}'" do
`Adding` or `Discovering`?

2016-09-29 20:22 UTC, tmiotto commented on resources/power_device.rb
> +  unless remove
Where this `remove` is coming from, and why is it here?

2016-09-30 11:38 UTC, hdiomede commented on resources/power_device.rb
> +  unless remove
Remove is from the resource base, it returns true or false.
It searches as a standard power device if the remove fails then we search as it as an iPDU

2016-09-30 20:24 UTC, tmiotto commented on resources/power_device.rb
> +  unless remove
Okay, got it. I would just add a comment there explaining the workflow

2016-10-03 13:47 UTC, tmiotto approved these changes

2016-10-03 13:47 UTC, merged