PR for config changes #API3000
HewlettPackard/oneview-chef pull request #506
Opened 2021-06-29 09:07 UTC by VenkateshRavula

### Description
PR for config changes #API3000

### Issues Resolved

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [ ] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

2021-06-29 09:16 UTC, yuvirani requested changes
Update attributes/default.rb with 6.2.0 which is used in automation.

2021-06-30 06:32 UTC, VenkateshRavula commented
> Update attributes/default.rb with 6.2.0 which is used in automation.

done

2021-07-01 04:41 UTC, yuvirani approved these changes

2021-07-01 05:29 UTC, AsisBagga approved these changes

2021-07-01 05:32 UTC, merged